### ISSUE TITLE
Filetool should listen to any changes in file system

### ISSUE THREAD

**Issue by arturbosch** [Grumnir/IDEmm#30]
Scenario: Open a project, go to your file manager, add a file, look at the filetool -> Added file is not displayed

**Comment by Grumnir** [comment]
This will most likly be done together with the feature to make changes to the filesystem from within the IDE. I will leave this here as a reminder

**Comment by Grumnir** [comment]
https://docs.oracle.com/javase/tutorial/essential/io/notification.html looks promissing

**Comment by Grumnir** [comment]
It is more likely to be handled in #34
